"""
Orchestration Schemas for CricGPT.

This module defines Pydantic v2 models representing query requests, query arguments,
planner query plans, execution results, and full orchestration responses.
"""

from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field, field_validator

from orchestration.intents import Intent


class QuestionRequest(BaseModel):
    """
    Represents an incoming natural language user question.
    """

    question: str

    @field_validator("question", mode="before")
    @classmethod
    def validate_question(cls, v: Any) -> str:
        """Strip whitespace and reject empty or whitespace-only strings."""
        if not isinstance(v, str):
            raise ValueError("Question must be a string.")
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Question cannot be empty or whitespace only.")
        return cleaned


class QueryArguments(BaseModel):
    """
    Represents extracted query entities and parameters.
    """

    player_name: Optional[str] = None
    batter: Optional[str] = None
    bowler: Optional[str] = None
    team_name: Optional[str] = None
    team1: Optional[str] = None
    team2: Optional[str] = None
    venue_name: Optional[str] = None
    match_id: Optional[int] = None
    limit: Optional[int] = None

    @field_validator("match_id")
    @classmethod
    def validate_match_id(cls, v: Optional[int]) -> Optional[int]:
        """Ensure match_id is strictly positive if provided."""
        if v is not None and v <= 0:
            raise ValueError("match_id must be greater than 0.")
        return v

    @field_validator("limit")
    @classmethod
    def validate_limit(cls, v: Optional[int]) -> Optional[int]:
        """Ensure limit is strictly positive if provided."""
        if v is not None and v <= 0:
            raise ValueError("limit must be greater than 0.")
        return v


class QueryPlan(BaseModel):
    """
    Represents an immutable execution plan generated by the planner component.
    """

    model_config = ConfigDict(frozen=True)

    version: str = "1.0"
    intent: Intent
    arguments: QueryArguments = Field(default_factory=QueryArguments)
    confidence: float
    source: str
    requires_clarification: bool = False
    clarification_message: Optional[str] = None

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        """Ensure confidence is between 0.0 and 1.0 inclusive."""
        if not (0.0 <= v <= 1.0):
            raise ValueError("confidence must be between 0.0 and 1.0 inclusive.")
        return v

    @field_validator("source", mode="before")
    @classmethod
    def validate_source(cls, v: Any) -> str:
        """Ensure source is a non-empty string."""
        if not isinstance(v, str):
            raise ValueError("source must be a string.")
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("source cannot be empty or whitespace only.")
        return cleaned


class ExecutionResult(BaseModel):
    """
    Represents the result of executing a query plan.
    """

    success: bool
    intent: Intent
    result: Any = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class OrchestrationResponse(BaseModel):
    """
    Represents the end-to-end response returned by the orchestration layer.
    """

    success: bool
    question: str
    plan: Optional[QueryPlan] = None
    result: Optional[ExecutionResult] = None
    answer: Optional[str] = None
